p8105_hw2_yc4804
================
Yilin Cai
2025-10-01

## Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'
    ## 
    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

``` r
# clean pols-month.csv
pols <- read_csv("/Users/caiyilin/Desktop/p8105_hw2_yc4804/fivethirtyeight_datasets/pols-month.csv") %>%
  # split mon into year / month / day
  separate(mon, into = c("year", "month", "day"), sep = "[-/]") %>%
  mutate(
    year  = as.integer(year),
    month = as.integer(month),
    month = month.name[month],  # replace number with month name
    president = if_else(prez_gop == 1, "gop", "dem")  # collapse prez indicators
  ) %>%
  select(-day, -prez_gop, -prez_dem) %>%
  relocate(year, month)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# clean snp.csv
snp <- read_csv("fivethirtyeight_datasets/snp.csv") %>%
  clean_names() %>%
  # correct split: YEAR / MONTH / DAY
  separate(date, into = c("year","month","day"), sep = "/", convert = TRUE) %>%
  mutate(
    # handle 2-digit years properly
    year = if_else(year < 100,
                   if_else(year >= 50, year + 1900, year + 2000),
                   year),
    month = factor(month, levels = 1:12, labels = month.name)
  ) %>%
  arrange(year, as.integer(month)) %>%
  relocate(year, month) %>%
  select(-day)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# unemployment.csv

unemployment <- read_csv("fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(
    cols = -Year,
    names_to = "month",
    values_to = "unemployment"
  ) %>%
  mutate(
    year = Year,
    month = str_to_title(month),   # e.g. "Jan" → "Jan", make sure matches month names
    month = recode(month,
                   "Jan" = "January", "Feb" = "February", "Mar" = "March",
                   "Apr" = "April", "May" = "May", "Jun" = "June",
                   "Jul" = "July", "Aug" = "August", "Sep" = "September",
                   "Oct" = "October", "Nov" = "November", "Dec" = "December")
  ) %>%
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_snp_unemp <- pols %>%
  left_join(snp, by = c("year", "month")) %>%          # adds S&P 'close'
  left_join(unemployment, by = c("year", "month")) %>% # adds 'unemployment'
  arrange(year, match(month, month.name))

head(pols_snp_unemp)
```

    ## # A tibble: 6 × 11
    ##    year month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##   <dbl> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ## 1  1947 January       23      51     253      23      45     198 dem          NA
    ## 2  1947 February      23      51     253      23      45     198 dem          NA
    ## 3  1947 March         23      51     253      23      45     198 dem          NA
    ## 4  1947 April         23      51     253      23      45     198 dem          NA
    ## 5  1947 May           23      51     253      23      45     198 dem          NA
    ## 6  1947 June          23      51     253      23      45     198 dem          NA
    ## # ℹ 1 more variable: unemployment <dbl>

The pols-month dataset contains monthly counts of governors, senators,
and representatives by political party, along with an indicator of
whether the sitting president was Republican (gop) or Democrat (dem).
The snp dataset reports monthly closing values of the S&P 500 index,
spanning 1950 through 2012. The unemployment dataset gives monthly U.S.
unemployment percentages, tidied from wide to long format with
consistent month names. After merging these three sources by year and
month, the resulting dataset has 1571 rows and 11 columns, covering the
period from 1947 to 2015. Key variables include year, month, president,
congressional counts (gov_gop, sen_dem, etc.), the S&P 500 closing value
(close), and the unemployment rate (unemployment). For years before 1950
and after 2012, close is unavailable and appears as missing values,
reflecting the coverage limits of the stock market data.

## Problem 2

``` r
library(readxl)
library(dplyr)
library(lubridate)
library(janitor)

clean_trash <- function(sheet, wheel) {
  df <- read_excel("202509 Trash Wheel Collection Data.xlsx", 
                   sheet = sheet, skip = 1) %>%
    clean_names() %>%
    select(any_of(c(
      "dumpster","month","year","date",
      "weight_tons","volume_cubic_yards",
      "plastic_bottles","polystyrene","cigarette_butts",
      "glass_bottles","plastic_bags","wrappers",
      "sports_balls","homes_powered"
    ))) %>%
    filter(!is.na(dumpster)) %>%
    mutate(
      wheel = wheel,
      dumpster = as.integer(dumpster),
      year = as.integer(year),
      month = as.character(month),
      date = as.Date(date)
    )
  
  # If sports_balls missing, add it
  if (!"sports_balls" %in% names(df)) {
    df <- df %>% mutate(sports_balls = NA_integer_)
  } else {
    df <- df %>% mutate(sports_balls = as.integer(round(sports_balls)))
  }
  
  df
}

# Apply to each wheel
mr   <- clean_trash("Mr. Trash Wheel", "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
prof <- clean_trash("Professor Trash Wheel", "Professor Trash Wheel")
gwyn <- clean_trash("Gwynns Falls Trash Wheel", "Gwynnda")

# Combine
trash_all <- bind_rows(mr, prof, gwyn)
head(trash_all)
```

    ## # A tibble: 6 × 15
    ##   dumpster month  year date       weight_tons volume_cubic_yards plastic_bottles
    ##      <int> <chr> <int> <date>           <dbl>              <dbl>           <dbl>
    ## 1        1 May    2014 2014-05-16        4.31                 18            1450
    ## 2        2 May    2014 2014-05-16        2.74                 13            1120
    ## 3        3 May    2014 2014-05-16        3.45                 15            2450
    ## 4        4 May    2014 2014-05-17        3.1                  15            2380
    ## 5        5 May    2014 2014-05-17        4.06                 18             980
    ## 6        6 May    2014 2014-05-20        2.71                 13            1430
    ## # ℹ 8 more variables: polystyrene <dbl>, cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, wheel <chr>

``` r
# Summary values
n_obs <- nrow(trash_all)

prof_total_weight_tons <- trash_all %>%
  filter(wheel == "Professor Trash Wheel") %>%
  summarise(total = sum(weight_tons, na.rm = TRUE)) %>%
  pull(total)

gwynnda_cigs_june_2022 <- trash_all %>%
  filter(wheel == "Gwynnda", year(date) == 2022, month(date) == 6) %>%
  summarise(total = sum(cigarette_butts, na.rm = TRUE)) %>%
  pull(total)
```

The combined Trash Wheel dataset contains 1188 dumpster-level
observations from Mr. Trash Wheel, Professor Trash Wheel, and Gwynnda.
Each row represents one dumpster load and includes information such as
the date of collection (`date`), the dumpster identifier (`dumpster`),
the weight of trash collected in tons (`weight_tons`), and the volume in
cubic yards (`volume_cubic_yards`). The dataset also reports counts of
specific types of debris, including `plastic_bottles`, `polystyrene`,
`cigarette_butts`, and `sports_balls` (rounded to the nearest whole
number). Across all available years, Professor Trash Wheel collected a
total of 282.26 tons of trash. In June 2022 alone, Gwynnda collected
1.812^{4} cigarette butts.

## Problem 3

``` r
library(lubridate)
library(tidyverse)

# ---- read the two files ----
zip_meta <- read_csv("zillow_data/Zip Codes.csv", show_col_types = FALSE)
zori_raw <- read_csv("zillow_data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv", show_col_types = FALSE)

# --- standardize zip codes ---
zip_clean <- zip_meta %>%
  mutate(zip = str_pad(as.character(ZipCode), 5, pad = "0")) %>%
  select(zip, Neighborhood, County, `State FIPS`, `County Code`, `County FIPS`, `File Date`)

zori_clean <- zori_raw %>%
  mutate(zip = str_pad(as.character(RegionName), 5, pad = "0"))

# --- find rent columns (monthly series) ---
monthly_cols <- names(zori_raw)[str_detect(names(zori_raw), "^\\d{4}-\\d{2}-\\d{2}$")]

# --- merge and clean ---
final_dataset <- zori_clean %>%
  left_join(zip_clean, by = "zip") %>%
  mutate(
    # coalesce: keep only one county and one state column
    county = coalesce(CountyName, County),
    state  = coalesce(State, StateName)
  ) %>%
  select(
    zip, RegionID, SizeRank, state, City, Metro, county, Neighborhood,
    `State FIPS`, `County Code`, `County FIPS`, `File Date`,
    all_of(monthly_cols)
  ) %>%
  arrange(zip)

monthly_cols <- names(final_dataset)[str_detect(names(final_dataset), "^\\d{4}-\\d{2}-\\d{2}$")]

# tidy ZIP × month
final_long <- final_dataset %>%
  pivot_longer(all_of(monthly_cols), names_to = "date", values_to = "zori_rent") %>%
  mutate(date = ymd(date)) %>%
  arrange(zip, date)

# --- check result ---
head(final_long)
```

    ## # A tibble: 6 × 14
    ##   zip   RegionID SizeRank state City     Metro  county Neighborhood `State FIPS`
    ##   <chr>    <dbl>    <dbl> <chr> <chr>    <chr>  <chr>  <chr>               <dbl>
    ## 1 10001    61615     4444 NY    New York New Y… New Y… Chelsea and…           36
    ## 2 10001    61615     4444 NY    New York New Y… New Y… Chelsea and…           36
    ## 3 10001    61615     4444 NY    New York New Y… New Y… Chelsea and…           36
    ## 4 10001    61615     4444 NY    New York New Y… New Y… Chelsea and…           36
    ## 5 10001    61615     4444 NY    New York New Y… New Y… Chelsea and…           36
    ## 6 10001    61615     4444 NY    New York New Y… New Y… Chelsea and…           36
    ## # ℹ 5 more variables: `County Code` <chr>, `County FIPS` <dbl>,
    ## #   `File Date` <chr>, date <date>, zori_rent <dbl>

final_long is my final merged dataset.

``` r
library(knitr)

# monthly date columns in your wide table
# basic description
total_obs  <- nrow(final_long)
n_zip      <- n_distinct(final_long$zip)
n_neigh    <- n_distinct(drop_na(final_long, Neighborhood)$Neighborhood)

cat("total observation", total_obs, "\n",
    "Unique ZIPs:", n_zip, "\n",
    "Unique neighborhoods (non-missing):", n_neigh, "\n\n")
```

    ## total observation 17516 
    ##  Unique ZIPs: 149 
    ##  Unique neighborhoods (non-missing): 42

``` r
# ZIPs in zip_meta but not in Zillow (your final_dataset)
zips_zipfile <- zip_meta %>%
  transmute(zip = str_pad(as.character(ZipCode), width = 5, side = "left", pad = "0")) %>%
  distinct(zip) %>%
  pull()

zips_zillow <- final_dataset %>%
  distinct(zip) %>%
  pull()

missing_zips <- setdiff(zips_zipfile, zips_zillow) %>% sort()

cat("ZIPs in ZIP file but not in Zillow (first 15):",
    paste(head(missing_zips, 15), collapse = ", "), "\n\n")
```

    ## ZIPs in ZIP file but not in Zillow (first 15): 10008, 10020, 10041, 10043, 10045, 10047, 10048, 10055, 10072, 10080, 10081, 10082, 10087, 10101, 10102

Some ZIP codes in the city list don’t appear in Zillow’s dataset because
ZORI tracks residential rents only. Several NYC ZIPs are non-residential
or non-geographic—for example, 10020 (Rockefeller Center), 10041/10055
(large corporate buildings), and 10008 (PO-box only)—so there’s no
normal housing inventory to index. Others are discontinued or
historical, like 10048 (former World Trade Center). A few additional
ZIPs may be omitted simply because they have too few active rental
listings to produce a stable series.

``` r
# top 10 drop: Jan 2020 -> Jan 2021
county_to_borough <- c(
  "Bronx County"    = "Bronx",
  "Kings County"    = "Brooklyn",
  "New York County" = "Manhattan",
  "Queens County"   = "Queens",
  "Richmond County" = "Staten Island"
)

jan20 <- final_long %>% filter(date == ymd("2020-01-31")) %>%
  transmute(zip, borough = recode(county, !!!county_to_borough),
            Neighborhood, rent_2020_01 = zori_rent)

jan21 <- final_long %>% filter(date == ymd("2021-01-31")) %>%
  transmute(zip, rent_2021_01 = zori_rent)

top10_drop <- jan20 %>%
  inner_join(jan21, by = "zip") %>%
  mutate(change = rent_2021_01 - rent_2020_01) %>%
  arrange(change) %>%
  slice_head(n = 10)
```

    ## Warning in inner_join(., jan21, by = "zip"): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 66 of `x` matches multiple rows in `y`.
    ## ℹ Row 66 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

``` r
kable(top10_drop, digits = 0,
      caption = "Largest drop in ZORI rent: Jan 2021 vs Jan 2020 (negative = drop)")
```

| zip | borough | Neighborhood | rent_2020_01 | rent_2021_01 | change |
|:---|:---|:---|---:|---:|---:|
| 10007 | Manhattan | Lower Manhattan | 6334 | 5422 | -913 |
| 10069 | Manhattan | NA | 4623 | 3875 | -748 |
| 10009 | Manhattan | Lower East Side | 3406 | 2692 | -714 |
| 10016 | Manhattan | Gramercy Park and Murray Hill | 3731 | 3019 | -712 |
| 10001 | Manhattan | Chelsea and Clinton | 4108 | 3398 | -710 |
| 10002 | Manhattan | Lower East Side | 3645 | 2935 | -710 |
| 10004 | Manhattan | Lower Manhattan | 3150 | 2444 | -706 |
| 10038 | Manhattan | Lower Manhattan | 3573 | 2876 | -698 |
| 10012 | Manhattan | Greenwich Village and Soho | 3629 | 2942 | -686 |
| 10010 | Manhattan | Gramercy Park and Murray Hill | 3697 | 3012 | -685 |

Largest drop in ZORI rent: Jan 2021 vs Jan 2020 (negative = drop)

The largest year-over-year rent drops are highly concentrated in
Manhattan. Every ZIP in the top-10 is a Manhattan ZIP, and the
neighborhoods are the most central, office- and amenity-dense
areas—Lower Manhattan, Lower East Side, Chelsea/Clinton, Gramercy
Park/Murray Hill, and Greenwich Village/Soho. The biggest decline is
10007 (Lower Manhattan), falling from \$6,334 to \$5,422. Several others
show drops of \$685–\$748 (e.g., 10069, 10009, 10016, 10001, 10002,
10004, 10038, 10012, 10010). This pattern is consistent with
early-pandemic dynamics: remote work, shuttered offices, and reduced
tourism disproportionately hit expensive, core Manhattan markets, while
outer-borough ZIPs don’t appear in the steepest-drop list.
